<?php

namespace MauticPlugin\MauticNetSuiteBundle\Api\NetSuite;

class NetSuiteCountries
{
    private static $map = [
        '_afghanistan' => 'Afghanistan',
        '_alandIslands' => 'Åland Islands',
        '_albania' => 'Albania',
        '_algeria' => 'Algeria',
        '_americanSamoa' => 'United States',
        '_andorra' => 'Andorra',
        '_angola' => 'Angola',
        '_anguilla' => 'Anguilla',
        '_antarctica' => 'Antarctica',
        '_antiguaAndBarbuda' => 'Antigua and Barbuda',
        '_argentina' => 'Argentina',
        '_armenia' => 'Armenia',
        '_aruba' => 'Aruba',
        '_australia' => 'Australia',
        '_austria' => 'Austria',
        '_azerbaijan' => 'Azerbaijan',
        '_bahamas' => 'Bahamas',
        '_bahrain' => 'Bahrain',
        '_bangladesh' => 'Bangladesh',
        '_barbados' => 'Barbados',
        '_belarus' => 'Belarus',
        '_belgium' => 'Belgium',
        '_belize' => 'Belize',
        '_benin' => 'Benin',
        '_bermuda' => 'Bermuda',
        '_bhutan' => 'Bhutan',
        '_bolivia' => 'Bolivia',
        '_bonaireSaintEustatiusAndSaba' => 'Bonaire, Saint Eustatius and Saba',
        '_bosniaAndHerzegovina' => 'Bosnia and Herzegovina',
        '_botswana' => 'Botswana',
        '_bouvetIsland' => 'Bouvet Island',
        '_brazil' => 'Brazil',
        '_britishIndianOceanTerritory' => 'United Kingdom',
        '_bruneiDarussalam' => 'Brunei',
        '_bulgaria' => 'Bulgaria',
        '_burkinaFaso' => 'Burkina Faso',
        '_burundi' => 'Burundi',
        '_cambodia' => 'Cambodia',
        '_cameroon' => 'Cameroon',
        '_canada' => 'Canada',
        '_canaryIslands' => 'Spain',
        '_capeVerde' => 'Cape Verde',
        '_caymanIslands' => 'Cayman Islands',
        '_centralAfricanRepublic' => 'Central African Republic',
        '_ceutaAndMelilla' => 'Spain',
        '_chad' => 'Chad',
        '_chile' => 'Chile',
        '_china' => 'China',
        '_christmasIsland' => 'Australia',
        '_cocosKeelingIslands' => 'Australia',
        '_colombia' => 'Colombia',
        '_comoros' => 'Comoros',
        '_congoDemocraticPeoplesRepublic' => 'Democratic Republic of the Congo',
        '_congoRepublicOf' => 'Republic of the Congo',
        '_cookIslands' => 'Cook Islands',
        '_costaRica' => 'Costa Rica',
        '_coteDIvoire' => 'Ivory Coast',
        '_croatiaHrvatska' => 'Croatia',
        '_cuba' => 'Cuba',
        '_curacao',
        '_cyprus' => 'Cyprus',
        '_czechRepublic' => 'Czech Republic',
        '_denmark' => 'Denmark',
        '_djibouti' => 'Djibouti',
        '_dominica' => 'Dominica',
        '_dominicanRepublic' => 'Dominican Republic',
        '_eastTimor' => 'East Timor',
        '_ecuador' => 'Ecuador',
        '_egypt' => 'Egypt',
        '_elSalvador' => 'El Salvador',
        '_equatorialGuinea' => 'Equatorial Guinea',
        '_eritrea' => 'Eritrea',
        '_estonia' => 'Estonia',
        '_ethiopia' => 'Ethiopia',
        '_falklandIslands' => 'Falkland Islands',
        '_faroeIslands' => 'Denmark',
        '_fiji' => 'Fiji',
        '_finland' => 'Finland',
        '_france' => 'France',
        '_frenchGuiana' => 'French Guiana',
        '_frenchPolynesia' => ['French Polynesia', 'Tahiti'],
        '_frenchSouthernTerritories' => 'France',
        '_gabon' => 'Gabon',
        '_gambia' => 'Gambia',
        '_georgia' => 'Georgia',
        '_germany' => 'Germany',
        '_ghana' => 'Ghana',
        '_gibraltar' => 'Gibraltar',
        '_greece' => 'Greece',
        '_greenland' => 'Greenland',
        '_grenada' => 'Grenada',
        '_guadeloupe' => 'Guadeloupe',
        '_guam' => 'Guam',
        '_guatemala' => 'Guatemala',
        '_guernsey' => 'Guernsey',
        '_guinea' => 'Guinea',
        '_guineaBissau' => 'Guinea Bissau',
        '_guyana' => 'Guyana',
        '_haiti' => 'Haiti',
        '_heardAndMcDonaldIslands' => 'Heard Island and McDonald Islands',
        '_holySeeCityVaticanState' => 'Holy See',
        '_honduras' => 'Honduras',
        '_hongKong' => 'Hong Kong',
        '_hungary' => 'Hungary',
        '_iceland' => 'Iceland',
        '_india' => 'India',
        '_indonesia' => 'Indonesia',
        '_iranIslamicRepublicOf' => 'Iran',
        '_iraq' => 'Iraq',
        '_ireland' => 'Ireland',
        '_isleOfMan' => 'United Kingdom',
        '_israel' => 'Israel',
        '_italy' => 'Italy',
        '_jamaica' => 'Jamaica',
        '_japan' => 'Japan',
        '_jersey' => 'Jersey',
        '_jordan' => 'Jordan',
        '_kazakhstan' => 'Kazakhstan',
        '_kenya' => 'Kenya',
        '_kiribati' => 'Kiribati',
        '_koreaDemocraticPeoplesRepublic' => 'North Korea',
        '_koreaRepublicOf' => 'South Korea',
        '_kosovo' => 'Serbia',
        '_kuwait' => 'Kuwait',
        '_kyrgyzstan' => 'Kyrgyzstan',
        '_laoPeoplesDemocraticRepublic' => 'Laos',
        '_latvia' => 'Latvia',
        '_lebanon' => 'Lebanon',
        '_lesotho' => 'Lesotho',
        '_liberia' => 'Liberia',
        '_libya' => 'Libya',
        '_liechtenstein' => 'Liechtenstein',
        '_lithuania' => 'Lithuania',
        '_luxembourg' => 'Luxembourg',
        '_macau' => 'Macao',
        '_macedonia' => 'Macedonia',
        '_madagascar' => 'Madagascar',
        '_malawi' => 'Malawi',
        '_malaysia' => 'Malaysia',
        '_maldives' => 'Maldives',
        '_mali' => 'Mali',
        '_malta' => 'Malta',
        '_marshallIslands' => 'Marshall Islands',
        '_martinique' => 'Martinique',
        '_mauritania' => 'Mauritania',
        '_mauritius' => 'Mauritius',
        '_mayotte' => 'Mayotte',
        '_mexico' => 'Mexico',
        '_micronesiaFederalStateOf' => 'Micronesia',
        '_moldovaRepublicOf' => 'Moldova',
        '_monaco' => 'Monaco',
        '_mongolia' => 'Mongolia',
        '_montenegro' => 'Montenegro',
        '_montserrat' => 'Montserrat',
        '_morocco' => 'Morocco',
        '_mozambique' => 'Mozambique',
        '_myanmar' => 'Myanmar',
        '_namibia' => 'Namibia',
        '_nauru' => 'Nauru',
        '_nepal' => 'Nepal',
        '_netherlands' => 'Netherlands',
        '_newCaledonia' => 'New Caledonia',
        '_newZealand' => 'New Zealand',
        '_nicaragua' => 'Nicaragua',
        '_niger' => 'Niger',
        '_nigeria' => 'Nigeria',
        '_niue' => 'Niue',
        '_norfolkIsland' => 'Australia',
        '_northernMarianaIslands' => 'Northern Mariana Islands',
        '_norway' => 'Norway',
        '_oman' => 'Oman',
        '_pakistan' => 'Pakistan',
        '_palau' => 'Palau',
        '_panama' => 'Panama',
        '_papuaNewGuinea' => 'Papua New Guinea',
        '_paraguay' => 'Paraguay',
        '_peru' => 'Peru',
        '_philippines' => 'Philippines',
        '_pitcairnIsland' => 'Pitcairn',
        '_poland' => 'Poland',
        '_portugal' => 'Portugal',
        '_puertoRico' => 'Puerto Rico',
        '_qatar' => 'Qatar',
        '_reunionIsland' => 'Réunion',
        '_romania' => 'Romania',
        '_russianFederation' => 'Russia',
        '_rwanda' => 'Rwanda',
        '_saintBarthelemy' => 'Saint Barthelemy',
        '_saintHelena' => 'Saint Helena, Ascension and Tristan da Cunha',
        '_saintKittsAndNevis' => 'Saint Kitts and Nevis',
        '_saintLucia' => 'Saint Lucia',
        '_saintMartin' => 'Saint Martin',
        '_saintVincentAndTheGrenadines' => 'Saint Vincent and the Grenadines',
        '_samoa' => 'Samoa',
        '_sanMarino' => 'San Marino',
        '_saoTomeAndPrincipe' => 'Sao Tome and Principe',
        '_saudiArabia' => 'Saudi Arabia',
        '_senegal' => 'Senegal',
        '_serbia' => ['Serbia', 'Yugoslavia'],
        '_seychelles' => 'Seychelles',
        '_sierraLeone' => 'Sierra Leone',
        '_singapore' => 'Singapore',
        '_sintMaarten' => 'Netherlands',
        '_slovakRepublic' => 'Slovakia',
        '_slovenia' => 'Slovenia',
        '_solomonIslands' => 'Solomon Islands',
        '_somalia' => 'Somalia',
        '_southAfrica' => 'South Africa',
        '_southGeorgia' => 'South Georgia and the South Sandwich Islands',
        '_southSudan' => 'South Sudan',
        '_spain' => 'Spain',
        '_sriLanka' => 'Sri Lanka',
        '_stateOfPalestine' => 'Palestine',
        '_stPierreAndMiquelon' => 'Saint Pierre and Miquelon',
        '_sudan' => 'Sudan',
        '_suriname' => 'Suriname',
        '_svalbardAndJanMayenIslands' => 'Svalbard and Jan Mayen',
        '_swaziland' => 'Swaziland',
        '_sweden' => 'Sweden',
        '_switzerland' => 'Switzerland',
        '_syrianArabRepublic' => 'Syria',
        '_taiwan' => 'Taiwan',
        '_tajikistan' => 'Tajikistan',
        '_tanzania' => 'Tanzania',
        '_thailand' => 'Thailand',
        '_togo' => 'Togo',
        '_tokelau' => 'Tokelau',
        '_tonga' => 'Tonga',
        '_trinidadAndTobago' => 'Trinidad and Tobago',
        '_tunisia' => 'Tunisia',
        '_turkey' => 'Turkey',
        '_turkmenistan' => 'Turkmenistan',
        '_turksAndCaicosIslands' => 'Turks and Caicos Islands',
        '_tuvalu' => 'Tuvalu',
        '_uganda' => 'Uganda',
        '_ukraine' => 'Ukraine',
        '_unitedArabEmirates' => 'United Arab Emirates',
        '_unitedKingdom' => 'United Kingdom',
        '_unitedStates' => 'United States',
        '_uruguay' => 'Uruguay',
        '_uSMinorOutlyingIslands' => 'United States',
        '_uzbekistan' => 'Uzbekistan',
        '_vanuatu' => 'Vanuatu',
        '_venezuela' => 'Venezuela',
        '_vietnam' => 'Vietnam',
        '_virginIslandsBritish' => 'Virgin Islands (British)',
        '_virginIslandsUSA' => 'Virgin Islands (U.S.)',
        '_wallisAndFutunaIslands' => 'Wallis and Futuna',
        '_westernSahara' => 'Western Sahara',
        '_yemen' => 'Yemen',
        '_zambia' => 'Zambia',
        '_zimbabwe' => 'Zimbabwe',
    ];

    public static function convertToNetSuite($mauticCountry) {
        if (empty($mauticCountry)) {
            $country = '';
        } else {
            $country = array_search($mauticCountry, self::$map, true);

            if ($country === false) {
                foreach (self::$map as $nsCountry => $value) {
                    if (is_array($value) && in_array($mauticCountry, $value, true)) {
                        $country = $nsCountry;
                        break;
                    }
                }
            }

            if ($country === false) {
                $country = str_replace('\'s', 's', $mauticCountry);
                $country = preg_replace('/[[:^print:]]/', '', $country);
                $country = trim($country);
                $country = ucwords($country);
                $country = str_replace(' ', '', $country);
                $country = lcfirst($country);
                $country = '_' . $country;
            }
        }

        return $country;
    }

    public static function convertToMautic($netSuiteCountry) {
        if (array_key_exists($netSuiteCountry, self::$map)) {
            $country = self::$map[$netSuiteCountry];
            if (is_array($country)) {
                $country = reset($country);
            }
        } else {
            $country = $netSuiteCountry;
            $country = str_replace('_', '', $country);
            $country = preg_replace('/(?<! )[A-Z]/', ' $0', $country);
        }

        return $country;
    }
}
